name: kick-off
version: '0.1'
summary: Scripts used in the process of a Docker image build and/or used to trigger processes in a Docker container.
description: |
  Utility used as helper in the process of building parts of a Docker image, plus configurator
  to trigger processes when a container is launched, plus services daemon launcher, plus signal
  processor to communicate with such processes.
grade: stable
# Classic confinement was used to allow internal commands to run mounts on host system.
# Originally a couple of interfaces were tested, with no positive results.
confinement: classic

apps:
  githooks:
    command: usr/bin/kick-off

parts:
  githooks:
    plugin: dump
    source: src/